spring.application.name=sistemaLoja


spring.jpa.hibernate.ddl-auto = update

spring.datasource.username = root
spring.datasource.password = Wa99$!02
spring.datasource.url = jdbc:mysql://localhost:3306/loja
spring.jpa.database-plataform = org.hibernate.dialect.MySQL8Dialect


